### ISSUE TITLE
Performance: Move up into HEAD

### ISSUE THREAD

**Issue by eaglerainbow** [SteNuf/Medikamentplanner#6]
https://github.com/SteNuf/Medikamentplanner/blob/4e982e74695509ae9a353958c5c9e5f359ca139e/mediplanertest.html#L69

Move the loading of the script up to the head. Defer execution if necessary.
==> improves performance as network loading JS file can be triggered already at the beginning of parsing - and does not require the canvas to be rendered first.

**Comment by SteNuf** [comment]
Work done
